import Foundation

enum AppLanguage: String, CaseIterable {
    case tr
    case en
    case fr
    case es

    static func resolve(_ preferredLanguages: [String]) -> AppLanguage {
        for identifier in preferredLanguages {
            let code = identifier
                .lowercased()
                .components(separatedBy: CharacterSet(charactersIn: "-_"))
                .first ?? ""
            if let language = AppLanguage(rawValue: code) {
                return language
            }
        }
        return .en
    }

    var locale: Locale { Locale(identifier: rawValue) }
}

enum L10nKey {
    case credentialPermissionRequired, grantCredentialAccess, lastKnownUsage
    case noAccounts, refreshNow, accounts, quit, loading, error
    case fiveHour, sevenDay, sevenDaySonnet, sevenDayOpus, oauthApps, cowork, updated
    case addProfile, removeAccount, pickerTitle, select
    case missingClaudeJSON, profileAlreadyAdded
    case accountName, accountNameHelp, add, cancel, accountNameEmpty, defaultAccountLabel
    case usageUsed, extraUsageWithLimit, extraUsage
    case resetDaysHours, resetHours, resetMinutes
    case keychainReadFailed, malformedCredential
    case missingRefreshToken, missingScopes, cliNotFound, loginRefreshFailed
    case invalidAnthropicResponse, anthropicHTTPFailed
    case accountStoreUnavailable
    case sessionExpired, refreshTokenExpiring
    case confirmRemoveAccount, removeAccountHelp
    case reconnectProfile, credentialCleanupFailed
    case defaultProfileProtected
    case journalExtra, journalTime, journalMeasurement, journalStatus, journalPeriod, journalPercent, journalReset, journalAvailable, journalMissing, journalSpent, journalBudget
    case journalOpen, journalWriteFailed, journalSampled, journalGap, journalFirst, journalRecovered
    case journalWindow, journalUnknownReset, journalNewPeriod, journalResetChanged, journalUnchanged
    case journalIncrease, journalDecrease, journalLimitReached, journalNearLimit, journalNoWindows, journalUnavailable
}

enum L10n {
    static var language: AppLanguage {
        AppLanguage.resolve(Locale.preferredLanguages)
    }

    static func text(_ key: L10nKey, language: AppLanguage? = nil) -> String {
        let selected = language ?? self.language
        return translations[selected]?[key] ?? translations[.en]![key]!
    }

    static func format(
        _ key: L10nKey,
        _ arguments: CVarArg...,
        language: AppLanguage? = nil
    ) -> String {
        let selected = language ?? self.language
        return String(
            format: text(key, language: selected),
            locale: selected.locale,
            arguments: arguments
        )
    }

    private static let translations: [AppLanguage: [L10nKey: String]] = [
        .tr: [
            .journalExtra: "Ek kullanım",
            .journalTime: "Saat",
            .journalMeasurement: "Ölçüm",
            .journalStatus: "Durum",
            .journalPeriod: "Dönem",
            .journalPercent: "Kullanım",
            .journalReset: "Sıfırlanma",
            .journalAvailable: "Güncel",
            .journalMissing: "Veri yok",
            .journalSpent: "Harcama ($)",
            .journalBudget: "Limit ($)",
            .credentialPermissionRequired: "Erişim izni gerekiyor",
            .grantCredentialAccess: "Erişime izin ver…",
            .lastKnownUsage: "Son başarılı ölçüm (güncel değil)",
            .journalOpen: "Kullanım günlüğünü aç",
            .journalWriteFailed: "Günlük klasörüne erişilemedi veya kayıt yazılamadı. Disk alanını ve izinleri kontrol et.",
            .journalSampled: "Ölçüm zamanı: %@",
            .journalGap: "Son başarılı kayıt %.1f saat önceydi. Aradaki kullanım bilinmiyor; eksik saatler doldurulmadı.",
            .journalFirst: "İlk ölçüm; karşılaştırılabilecek önceki kayıt yok.",
            .journalRecovered: "Güncel kullanım bilgisine yeniden erişildi.",
            .journalWindow: "%@: %.1f%% kullanıldı · Sıfırlanma: %@",
            .journalUnknownReset: "Bilinmiyor",
            .journalNewPeriod: "Yeni kullanım dönemi gözlendi; önceki dönemle yüzde farkı hesaplanmadı.",
            .journalResetChanged: "Sıfırlanma zamanı değişti; bu iki ölçüm karşılaştırılmadı.",
            .journalUnchanged: "Önceki saatlik ölçüme göre değişmedi.",
            .journalIncrease: "Kullanım arttı: %.1f%% → %.1f%% (+%.1f yüzde puan).",
            .journalDecrease: "Bildirilen kullanım azaldı: %.1f%% → %.1f%% (%.1f yüzde puan). Sıfırlanma varsayılmadı.",
            .journalLimitReached: "Bildirilen limit doluluğu %100 veya üzerinde.",
            .journalNearLimit: "Limit yaklaşıyor; bildirilen kalan pay %.1f%%.",
            .journalNoWindows: "Yanıtta kullanım penceresi bulunmuyor.",
            .journalUnavailable: "Güncel ölçüm yok. İstek başarısız, henüz tamamlanmamış veya son ölçüm altı dakikadan eski olabilir. Yüzde tahmin edilmedi.",
            .defaultProfileProtected: "Varsayılan ~/.claude profili otomatik değiştirilmez. Ayrı bir CLAUDE_CONFIG_DIR profili kullan.",
            .reconnectProfile: "Profili yeniden bağla",
            .credentialCleanupFailed: "Hesap kaldırıldı ancak ClaudeHub'ın Keychain kopyası silinemedi. Keychain Erişimi'nde com.tugkanboz.claudehub.credentials kaydını kontrol et. Claude Code kaydı değiştirilmedi.",
            .confirmRemoveAccount: "%@ kaldırılsın mı?",
            .removeAccountHelp: "Hesap ClaudeHub'dan kaldırılacak. Claude Code profil klasörü ve oturumu silinmez.",
            .sessionExpired: "Oturum süresi doldu. Bu profilin CLAUDE_CONFIG_DIR değeriyle claude auth login çalıştır, ardından yeniden bağla.",
            .refreshTokenExpiring: "Oturum yenileme süresi dolmak üzere veya doldu. Bu profil için tekrar giriş yap.",
            .accountStoreUnavailable: "Hesap dosyası okunamadı veya kaydedilemedi. Mevcut dosya korundu; bozuk JSON için .bak yedeği oluşturulmaya çalışıldı. accounts.json dosyasını kontrol edip uygulamayı yeniden aç. Hesap değişiklikleri devre dışı.",
            .noAccounts: "Henüz hesap eklenmedi",
            .refreshNow: "Şimdi yenile",
            .accounts: "Hesaplar",
            .quit: "ClaudeHub'dan çık",
            .loading: "Yükleniyor…",
            .error: "Hata: %@",
            .fiveHour: "5 saat",
            .sevenDay: "7 gün",
            .sevenDaySonnet: "7 gün Sonnet",
            .sevenDayOpus: "7 gün Opus",
            .oauthApps: "OAuth uygulamaları",
            .cowork: "Cowork",
            .updated: "Güncellendi: %@",
            .addProfile: "Mevcut Claude profilini ekle…",
            .removeAccount: "Hesap kaldır",
            .pickerTitle: "Claude Code profil klasörünü seç",
            .select: "Seç",
            .missingClaudeJSON: "Bu klasörde .claude.json bulunamadı. Önce bu CLAUDE_CONFIG_DIR ile Claude Code'a giriş yap.",
            .profileAlreadyAdded: "Bu profil zaten ekli.",
            .accountName: "Hesap adı",
            .accountNameHelp: "Menüde görünecek kısa adı yaz.",
            .add: "Ekle",
            .cancel: "İptal",
            .accountNameEmpty: "Hesap adı boş olamaz.",
            .defaultAccountLabel: "Claude hesabı",
            .usageUsed: "%@: %@ kullanıldı",
            .extraUsageWithLimit: "Ek kullanım: $%.2f / $%.2f",
            .extraUsage: "Ek kullanım: $%.2f",
            .resetDaysHours: "%dg %dsa sonra sıfırlanır",
            .resetHours: "%dsa sonra sıfırlanır",
            .resetMinutes: "%ddk sonra sıfırlanır",
            .keychainReadFailed: "Keychain kaydı okunamadı (%d). Bu profil Claude Code ile giriş yapmış mı?",
            .malformedCredential: "Claude Code kimlik kaydı beklenen biçimde değil.",
            .missingRefreshToken: "Refresh token yok; bu profil için bir kez claude auth login çalıştır.",
            .missingScopes: "OAuth scope bilgisi yok; bu profil için bir kez claude auth login çalıştır.",
            .cliNotFound: "Claude Code bulunamadı. Claude Code'u kurup ClaudeHub'ı yeniden aç.",
            .loginRefreshFailed: "Claude Code oturumu yenileyemedi; bu profil için bir kez claude auth login çalıştır.",
            .invalidAnthropicResponse: "Anthropic geçersiz bir yanıt döndürdü.",
            .anthropicHTTPFailed: "Anthropic isteği HTTP %d ile başarısız oldu.",
        ],
        .en: [
            .journalExtra: "Extra usage",
            .journalTime: "Time",
            .journalMeasurement: "Measured",
            .journalStatus: "Status",
            .journalPeriod: "Period",
            .journalPercent: "Usage",
            .journalReset: "Reset",
            .journalAvailable: "Available",
            .journalMissing: "No data",
            .journalSpent: "Spent ($)",
            .journalBudget: "Limit ($)",
            .credentialPermissionRequired: "Access permission required",
            .grantCredentialAccess: "Allow access…",
            .lastKnownUsage: "Last successful measurement (not current)",
            .journalOpen: "Open Usage Journal",
            .journalWriteFailed: "Could not access the journal folder or write a record. Check disk space and permissions.",
            .journalSampled: "Measured at: %@",
            .journalGap: "The last successful record was %.1f hours ago. Usage in the gap is unknown; missing hours were not filled in.",
            .journalFirst: "First measurement; no earlier record is available for comparison.",
            .journalRecovered: "Current usage information is available again.",
            .journalWindow: "%@: %.1f%% used · Resets at: %@",
            .journalUnknownReset: "Unknown",
            .journalNewPeriod: "A new usage period was observed; no percentage delta was calculated across periods.",
            .journalResetChanged: "The reset time changed; these measurements were not compared.",
            .journalUnchanged: "Unchanged since the previous hourly measurement.",
            .journalIncrease: "Usage increased: %.1f%% → %.1f%% (+%.1f percentage points).",
            .journalDecrease: "Reported usage decreased: %.1f%% → %.1f%% (%.1f percentage points). A reset was not assumed.",
            .journalLimitReached: "Reported limit utilization is at or above 100%.",
            .journalNearLimit: "Approaching the limit; reported remaining share is %.1f%%.",
            .journalNoWindows: "No usage windows were included in the response.",
            .journalUnavailable: "No current measurement. The request may have failed, may still be pending, or the last sample is over six minutes old. No percentage was estimated.",
            .defaultProfileProtected: "The default ~/.claude profile is not modified automatically. Use a separate CLAUDE_CONFIG_DIR profile.",
            .reconnectProfile: "Reconnect Profile",
            .credentialCleanupFailed: "The account was removed, but its ClaudeHub Keychain copy could not be deleted. Check com.tugkanboz.claudehub.credentials in Keychain Access. The Claude Code item was not changed.",
            .confirmRemoveAccount: "Remove %@?",
            .removeAccountHelp: "The account will be removed from ClaudeHub. Its Claude Code profile folder and session will not be deleted.",
            .sessionExpired: "Session expired. Run claude auth login with this profile’s CLAUDE_CONFIG_DIR, then reconnect.",
            .refreshTokenExpiring: "Session renewal expires soon or has expired. Sign in again for this profile.",
            .accountStoreUnavailable: "The account file could not be read or saved. The existing file was preserved; a .bak backup was attempted for invalid JSON. Check accounts.json and restart the app. Account changes are disabled.",
            .noAccounts: "No accounts added yet",
            .refreshNow: "Refresh Now",
            .accounts: "Accounts",
            .quit: "Quit ClaudeHub",
            .loading: "Loading…",
            .error: "Error: %@",
            .fiveHour: "5 hours",
            .sevenDay: "7 days",
            .sevenDaySonnet: "7-day Sonnet",
            .sevenDayOpus: "7-day Opus",
            .oauthApps: "OAuth applications",
            .cowork: "Cowork",
            .updated: "Updated: %@",
            .addProfile: "Add Existing Claude Profile…",
            .removeAccount: "Remove Account",
            .pickerTitle: "Select Claude Code Profile Folder",
            .select: "Select",
            .missingClaudeJSON: "This folder does not contain .claude.json. Sign in to Claude Code with this CLAUDE_CONFIG_DIR first.",
            .profileAlreadyAdded: "This profile is already added.",
            .accountName: "Account Name",
            .accountNameHelp: "Enter a short name to display in the menu.",
            .add: "Add",
            .cancel: "Cancel",
            .accountNameEmpty: "Account name cannot be empty.",
            .defaultAccountLabel: "Claude account",
            .usageUsed: "%@: %@ used",
            .extraUsageWithLimit: "Extra usage: $%.2f / $%.2f",
            .extraUsage: "Extra usage: $%.2f",
            .resetDaysHours: "resets in %dd %dh",
            .resetHours: "resets in %dh",
            .resetMinutes: "resets in %dmin",
            .keychainReadFailed: "Could not read the Keychain item (%d). Is this profile signed in to Claude Code?",
            .malformedCredential: "The Claude Code credential has an unexpected format.",
            .missingRefreshToken: "No refresh token. Run claude auth login once for this profile.",
            .missingScopes: "No OAuth scope information. Run claude auth login once for this profile.",
            .cliNotFound: "Claude Code was not found. Install Claude Code and reopen ClaudeHub.",
            .loginRefreshFailed: "Claude Code could not renew the session. Run claude auth login once for this profile.",
            .invalidAnthropicResponse: "Anthropic returned an invalid response.",
            .anthropicHTTPFailed: "The Anthropic request failed with HTTP %d.",
        ],
        .fr: [
            .journalExtra: "Usage supplémentaire",
            .journalTime: "Heure",
            .journalMeasurement: "Mesure",
            .journalStatus: "État",
            .journalPeriod: "Période",
            .journalPercent: "Utilisation",
            .journalReset: "Réinitialisation",
            .journalAvailable: "Disponible",
            .journalMissing: "Indisponible",
            .journalSpent: "Dépense ($)",
            .journalBudget: "Limite ($)",
            .credentialPermissionRequired: "Autorisation d’accès requise",
            .grantCredentialAccess: "Autoriser l’accès…",
            .lastKnownUsage: "Dernière mesure réussie (non actuelle)",
            .journalOpen: "Ouvrir le journal d’utilisation",
            .journalWriteFailed: "Impossible d’accéder au journal ou d’écrire une entrée. Vérifiez l’espace disque et les autorisations.",
            .journalSampled: "Mesure effectuée à : %@",
            .journalGap: "La dernière entrée valide date de %.1f heures. L’utilisation pendant cette période est inconnue ; les heures manquantes n’ont pas été reconstituées.",
            .journalFirst: "Première mesure ; aucune entrée antérieure à comparer.",
            .journalRecovered: "Les informations d’utilisation actuelles sont de nouveau disponibles.",
            .journalWindow: "%@ : %.1f%% utilisés · Réinitialisation : %@",
            .journalUnknownReset: "Inconnue",
            .journalNewPeriod: "Une nouvelle période d’utilisation a été observée ; aucun écart entre périodes n’a été calculé.",
            .journalResetChanged: "L’heure de réinitialisation a changé ; ces mesures n’ont pas été comparées.",
            .journalUnchanged: "Aucun changement depuis la mesure horaire précédente.",
            .journalIncrease: "Utilisation en hausse : %.1f%% → %.1f%% (+%.1f points de pourcentage).",
            .journalDecrease: "Utilisation déclarée en baisse : %.1f%% → %.1f%% (%.1f points de pourcentage). Aucune réinitialisation n’a été supposée.",
            .journalLimitReached: "Le taux d’utilisation déclaré atteint ou dépasse 100 %.",
            .journalNearLimit: "Limite proche ; part restante déclarée : %.1f%%.",
            .journalNoWindows: "La réponse ne contient aucune période d’utilisation.",
            .journalUnavailable: "Aucune mesure actuelle. La requête a pu échouer, être en cours ou la dernière mesure date de plus de six minutes. Aucun pourcentage n’a été estimé.",
            .defaultProfileProtected: "Le profil ~/.claude par défaut n’est pas modifié automatiquement. Utilisez un profil CLAUDE_CONFIG_DIR distinct.",
            .reconnectProfile: "Reconnecter le profil",
            .credentialCleanupFailed: "Le compte a été retiré, mais sa copie ClaudeHub n’a pas pu être supprimée du trousseau. Vérifiez com.tugkanboz.claudehub.credentials dans Trousseaux d’accès. L’élément Claude Code n’a pas été modifié.",
            .confirmRemoveAccount: "Supprimer %@ ?",
            .removeAccountHelp: "Le compte sera retiré de ClaudeHub. Son dossier de profil et sa session Claude Code ne seront pas supprimés.",
            .sessionExpired: "Session expirée. Exécutez claude auth login avec le CLAUDE_CONFIG_DIR de ce profil, puis reconnectez-le.",
            .refreshTokenExpiring: "Le renouvellement de session expire bientôt ou a expiré. Reconnectez-vous à ce profil.",
            .accountStoreUnavailable: "Impossible de lire ou enregistrer les comptes. Le fichier existant est conservé ; une sauvegarde .bak a été tentée pour le JSON invalide. Vérifiez accounts.json et relancez l’application. Les modifications sont désactivées.",
            .noAccounts: "Aucun compte ajouté",
            .refreshNow: "Actualiser maintenant",
            .accounts: "Comptes",
            .quit: "Quitter ClaudeHub",
            .loading: "Chargement…",
            .error: "Erreur : %@",
            .fiveHour: "5 heures",
            .sevenDay: "7 jours",
            .sevenDaySonnet: "Sonnet sur 7 jours",
            .sevenDayOpus: "Opus sur 7 jours",
            .oauthApps: "Applications OAuth",
            .cowork: "Cowork",
            .updated: "Mis à jour : %@",
            .addProfile: "Ajouter un profil Claude existant…",
            .removeAccount: "Supprimer un compte",
            .pickerTitle: "Sélectionner le dossier du profil Claude Code",
            .select: "Sélectionner",
            .missingClaudeJSON: "Ce dossier ne contient pas de fichier .claude.json. Connectez-vous d'abord à Claude Code avec ce CLAUDE_CONFIG_DIR.",
            .profileAlreadyAdded: "Ce profil est déjà ajouté.",
            .accountName: "Nom du compte",
            .accountNameHelp: "Saisissez un nom court à afficher dans le menu.",
            .add: "Ajouter",
            .cancel: "Annuler",
            .accountNameEmpty: "Le nom du compte ne peut pas être vide.",
            .defaultAccountLabel: "Compte Claude",
            .usageUsed: "%@ : %@ utilisés",
            .extraUsageWithLimit: "Utilisation supplémentaire : $%.2f / $%.2f",
            .extraUsage: "Utilisation supplémentaire : $%.2f",
            .resetDaysHours: "réinitialisation dans %dj %dh",
            .resetHours: "réinitialisation dans %dh",
            .resetMinutes: "réinitialisation dans %d min",
            .keychainReadFailed: "Impossible de lire l'élément du trousseau (%d). Ce profil est-il connecté à Claude Code ?",
            .malformedCredential: "L'identifiant Claude Code présente un format inattendu.",
            .missingRefreshToken: "Aucun refresh token. Exécutez claude auth login une fois pour ce profil.",
            .missingScopes: "Aucune information de scope OAuth. Exécutez claude auth login une fois pour ce profil.",
            .cliNotFound: "Claude Code est introuvable. Installez Claude Code puis relancez ClaudeHub.",
            .loginRefreshFailed: "Claude Code n'a pas pu renouveler la session. Exécutez claude auth login une fois pour ce profil.",
            .invalidAnthropicResponse: "Anthropic a renvoyé une réponse non valide.",
            .anthropicHTTPFailed: "La requête Anthropic a échoué avec le code HTTP %d.",
        ],
        .es: [
            .journalExtra: "Uso adicional",
            .journalTime: "Hora",
            .journalMeasurement: "Medición",
            .journalStatus: "Estado",
            .journalPeriod: "Periodo",
            .journalPercent: "Uso",
            .journalReset: "Reinicio",
            .journalAvailable: "Disponible",
            .journalMissing: "Sin datos",
            .journalSpent: "Gasto ($)",
            .journalBudget: "Límite ($)",
            .credentialPermissionRequired: "Se requiere permiso de acceso",
            .grantCredentialAccess: "Permitir acceso…",
            .lastKnownUsage: "Última medición correcta (no actual)",
            .journalOpen: "Abrir diario de uso",
            .journalWriteFailed: "No se pudo acceder al diario o escribir una entrada. Revisa el espacio en disco y los permisos.",
            .journalSampled: "Medición realizada: %@",
            .journalGap: "El último registro válido fue hace %.1f horas. El uso durante ese intervalo es desconocido; no se rellenaron las horas que faltan.",
            .journalFirst: "Primera medición; no hay un registro anterior para comparar.",
            .journalRecovered: "La información actual de uso vuelve a estar disponible.",
            .journalWindow: "%@: %.1f%% usado · Restablecimiento: %@",
            .journalUnknownReset: "Desconocido",
            .journalNewPeriod: "Se observó un nuevo período de uso; no se calculó una diferencia entre períodos.",
            .journalResetChanged: "La hora de restablecimiento cambió; estas mediciones no se compararon.",
            .journalUnchanged: "Sin cambios desde la medición horaria anterior.",
            .journalIncrease: "El uso aumentó: %.1f%% → %.1f%% (+%.1f puntos porcentuales).",
            .journalDecrease: "El uso indicado disminuyó: %.1f%% → %.1f%% (%.1f puntos porcentuales). No se supuso un restablecimiento.",
            .journalLimitReached: "El uso indicado del límite alcanza o supera el 100 %.",
            .journalNearLimit: "Cerca del límite; porcentaje restante indicado: %.1f%%.",
            .journalNoWindows: "La respuesta no incluye períodos de uso.",
            .journalUnavailable: "No hay una medición actual. La solicitud puede haber fallado, seguir pendiente o la última medición tiene más de seis minutos. No se estimó ningún porcentaje.",
            .defaultProfileProtected: "El perfil ~/.claude predeterminado no se modifica automáticamente. Usa un perfil CLAUDE_CONFIG_DIR separado.",
            .reconnectProfile: "Reconectar perfil",
            .credentialCleanupFailed: "La cuenta se eliminó, pero no se pudo borrar su copia de ClaudeHub del llavero. Revisa com.tugkanboz.claudehub.credentials en Acceso a Llaveros. No se modificó el elemento de Claude Code.",
            .confirmRemoveAccount: "¿Eliminar %@?",
            .removeAccountHelp: "La cuenta se eliminará de ClaudeHub. No se borrarán su carpeta de perfil ni su sesión de Claude Code.",
            .sessionExpired: "La sesión ha caducado. Ejecuta claude auth login con el CLAUDE_CONFIG_DIR de este perfil y vuelve a conectarlo.",
            .refreshTokenExpiring: "La renovación de sesión caduca pronto o ya caducó. Inicia sesión de nuevo en este perfil.",
            .accountStoreUnavailable: "No se pudo leer o guardar el archivo de cuentas. Se conservó el archivo existente y se intentó crear una copia .bak del JSON inválido. Revisa accounts.json y reinicia la app. Los cambios están desactivados.",
            .noAccounts: "Aún no se han añadido cuentas",
            .refreshNow: "Actualizar ahora",
            .accounts: "Cuentas",
            .quit: "Salir de ClaudeHub",
            .loading: "Cargando…",
            .error: "Error: %@",
            .fiveHour: "5 horas",
            .sevenDay: "7 días",
            .sevenDaySonnet: "Sonnet de 7 días",
            .sevenDayOpus: "Opus de 7 días",
            .oauthApps: "Aplicaciones OAuth",
            .cowork: "Cowork",
            .updated: "Actualizado: %@",
            .addProfile: "Añadir un perfil de Claude existente…",
            .removeAccount: "Eliminar cuenta",
            .pickerTitle: "Seleccionar carpeta del perfil de Claude Code",
            .select: "Seleccionar",
            .missingClaudeJSON: "Esta carpeta no contiene .claude.json. Inicia sesión en Claude Code con este CLAUDE_CONFIG_DIR primero.",
            .profileAlreadyAdded: "Este perfil ya está añadido.",
            .accountName: "Nombre de la cuenta",
            .accountNameHelp: "Escribe un nombre corto para mostrarlo en el menú.",
            .add: "Añadir",
            .cancel: "Cancelar",
            .accountNameEmpty: "El nombre de la cuenta no puede estar vacío.",
            .defaultAccountLabel: "Cuenta de Claude",
            .usageUsed: "%@: %@ usado",
            .extraUsageWithLimit: "Uso adicional: $%.2f / $%.2f",
            .extraUsage: "Uso adicional: $%.2f",
            .resetDaysHours: "se restablece en %dd %dh",
            .resetHours: "se restablece en %dh",
            .resetMinutes: "se restablece en %d min",
            .keychainReadFailed: "No se pudo leer el elemento del llavero (%d). ¿Este perfil ha iniciado sesión en Claude Code?",
            .malformedCredential: "La credencial de Claude Code tiene un formato inesperado.",
            .missingRefreshToken: "No hay refresh token. Ejecuta claude auth login una vez para este perfil.",
            .missingScopes: "No hay información de scopes OAuth. Ejecuta claude auth login una vez para este perfil.",
            .cliNotFound: "No se encontró Claude Code. Instala Claude Code y vuelve a abrir ClaudeHub.",
            .loginRefreshFailed: "Claude Code no pudo renovar la sesión. Ejecuta claude auth login una vez para este perfil.",
            .invalidAnthropicResponse: "Anthropic devolvió una respuesta no válida.",
            .anthropicHTTPFailed: "La solicitud a Anthropic falló con HTTP %d.",
        ],
    ]
}
